name: Framework Quality

on:
  push:
    branches: [main, develop]
    paths:
      - 'packages/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'packages/**'

jobs:
  framework-tests:
    name: Framework Package Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build framework packages
        run: |
          pnpm --filter @atriz/core build
          pnpm --filter @atriz/auth build

      - name: Test @atriz/core
        run: pnpm --filter @atriz/core test:coverage

      - name: Test @atriz/auth
        run: pnpm --filter @atriz/auth test:coverage

      - name: Check coverage thresholds
        run: |
          echo "Checking coverage thresholds..."
          # Add coverage threshold checks here if needed

  framework-lint:
    name: Framework Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint framework packages
        run: |
          pnpm --filter @atriz/core lint
          pnpm --filter @atriz/auth lint

      - name: Type check framework packages
        run: |
          pnpm --filter @atriz/core build
          pnpm --filter @atriz/auth build

