name: Framework Quality

on:
    push:
        branches: [main, develop]
        paths:
            - 'packages/**'
    pull_request:
        branches: [main, develop]
        paths:
            - 'packages/**'

jobs:
    framework-tests:
        name: Framework Package Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 9

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build core package
              run: pnpm --filter @atriz/core build

            - name: Test @atriz/core
              run: pnpm --filter @atriz/core test:coverage

            - name: Upload coverage reports
              uses: codecov/codecov-action@v4
              with:
                  file: ./packages/core/coverage/lcov.info
                  flags: core
                  name: core-coverage
                  fail_ci_if_error: false

    framework-lint:
        name: Framework Code Quality
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 9

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint core package
              run: pnpm --filter @atriz/core lint:check

            - name: Type check core package
              run: pnpm --filter @atriz/core type-check

    security-audit:
        name: Security Audit
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 9

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run security audit
              run: pnpm audit --audit-level moderate

            - name: Check for known vulnerabilities
              run: pnpm audit --audit-level high --json > audit-results.json || true

            - name: Upload audit results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: security-audit-results
                  path: audit-results.json
